export type TimeRange = '24h' | '7d' | '30d';
export type RunStatus = 'success' | 'error' | 'rate-limited' | 'running' | 'unknown';
export type AgentStatus = 'idle' | 'busy' | 'error' | 'offline' | 'rate-limited';
export interface DashboardSource { name: string; path: string; live: boolean; purpose: string; }
export interface TokenUsageRecord { id: string; agentId: string; sessionKey: string; startedAt: string; endedAt?: string; provider: string; model: string; status: RunStatus; inputTokens: number; outputTokens: number; totalTokens: number; cacheReadTokens?: number; latencyMs?: number; tokensPerSecond?: number; }
export interface TokenUsageResponse { generatedAt: string; refreshMs: number; liveSources: string[]; filterOptions: { agents: string[]; providers: string[]; models: string[]; statuses: RunStatus[]; }; summaryCards: Array<{ label: string; value: string; helpText?: string; }>; buckets: Array<{ label: string; totalsByModel: Record<string, number>; inputTokens: number; outputTokens: number; requests: number; }>; performanceSeries: Array<{ timestamp: string; model: string; tokensPerSecond: number; }>; breakdown: Array<{ model: string; provider: string; requests: number; inputTokens: number; outputTokens: number; avgTokensPerSecond?: number; avgLatencyMs?: number; errorCount: number; }>; limits: { providerLimitsKnown: boolean; windows: Array<{ window: string; trackedTokens: number; trackedRequests: number; note: string; }>; }; records: TokenUsageRecord[]; notes: string[]; }
export interface AgentTask { id: string; title: string; status: 'outstanding' | 'current' | 'completed' | 'failed'; startedAt?: string; endedAt?: string; durationMs?: number; model?: string; provider?: string; tokensIn?: number; tokensOut?: number; retryCount?: number; failureReason?: string; source: string; }
export interface AgentCard { agentId: string; name: string; status: AgentStatus; queueCount: number; tasksInProgress: number; completedLast24h: number; lastActivityAt?: string; primaryModel?: string; fallbackModels: string[]; outstandingTasks: AgentTask[]; currentTasks: AgentTask[]; completedTasks: AgentTask[]; failuresLast24h: AgentTask[]; tokenUsageSummary: { inputTokens: number; outputTokens: number; requests: number; }; detailNotes: string[]; }
export interface AgentsResponse { generatedAt: string; refreshMs: number; liveSources: string[]; filterOptions: { agents: string[]; statuses: AgentStatus[]; }; agents: AgentCard[]; notes: string[]; }
export interface DashboardSnapshot { tokenUsage: TokenUsageResponse; agents: AgentsResponse; dataSources: DashboardSource[]; }
